name: Scala CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Install uncached tools
        run: source .github/workflows/tools.sh && install_tools

      - name: Install SpinalHDL
        run: (cd .. && git clone https://github.com/SpinalHDL/SpinalHDL.git -b dev)

      - name: Compile
        run: sbt clean compile

      - name: Test
        run: sbt test
